```{r echo = FALSE, results = 'hide', message=FALSE, warning = FALSE, fig.keep='none'}
autogen_color <- TRUE # TRUE/FALSE
file_sources <- list.files(path = c('admin/setup_scripts/00_global_scripts','admin/setup_scripts/01_phyto_scripts'), pattern = '.R$', full.names=TRUE, recursive = TRUE)
sapply(file_sources, source, .GlobalEnv)
```

```{r, echo = FALSE, results = 'hide'}
plt_org_density <- function(region){
  # create algal df and assign color palette
  df <- alg_dfs(df_phyto_year, 'main', region)
  df <- assign_colors(df, 'AlgalGroup', 'Set2')

  plts <- list()
  # create the two plots; cyano is separate b/c it's a different scale
  if('Cyanobacteria' %in% unique(df$AlgalGroup)){
    p1 <- ggplot2::ggplot(df[df$AlgalGroup != 'Cyanobacteria',], ggplot2::aes(Month, Units_per_mL, fill = color))+
      ggplot2::geom_col(position = 'dodge') +
      ggplot2::theme_bw() +
      ggplot2::theme(legend.position = 'none') +
      ggplot2::scale_fill_identity()    
    
    plts[[1]] <- p1
  }
    p2 <- ggplot2::ggplot(df, ggplot2::aes(Month, Units_per_mL, fill = color))+
      ggplot2::geom_col(position = 'dodge') +
      ggplot2::theme_bw() +
      ggplot2::theme(legend.position = 'none') +
      ggplot2::scale_fill_identity()
    
    # index p2 in list based on if p1 exists
    if(length(plts) == 1){
      i <- 2
    } else {
      i <- 1
    }
    
  plts[[i]] <- p2
  
  return(plts)
}


```

```{r}
algal_plts()
```


```{r, results = 'asis'}
purrr::walk(plts, print)
```

```{r}
region_plts <- function(region){
  plt_wq <- wq_avg_plt(region)
  
  cowplot::plot_grid(plotlist = list(plt_wq))
  
  org_plts <- plt_org_density(region)
  
  cowplot::plot_grid(plotlist = org_plts, ncol = 2)
}

region_plts('Confluence')
```


```{r}
# old version

# alg_dfs <- function(df, type, region){
#   if (region != 'none'){
#     df <- df %>%
#       dplyr::filter(Region == region) %>%
#       dplyr::mutate(Month = factor(months(SampleDate), levels = month.name, labels = month.abb))
#     
#     group_var <- dplyr::quos(AlgalGroup, Region, Month)
#   } else {
#     group_var <- dplyr::quos(AlgalGroup)
#   }
#   
#   df_comp <- df %>%
#     dplyr::mutate(
#       AlgalGroup =
#         dplyr::case_when(grepl('Diatoms', AlgalGroup) ~ 'Diatoms',
#                          TRUE ~ AlgalGroup)
#     ) %>%
#     dplyr::group_by(!!!group_var) %>%
#     dplyr::summarise(tot = nrow(.),
#                      count = dplyr::n(),
#                      per = 100*(dplyr::n() / nrow(.)),
#                      Units_per_mL = sum(Units_per_mL)) %>%
#     dplyr::distinct()
#   
#   if(type == 'raw'){
#     df_return <- df_comp
#     
#   } else if (type == 'main'){
#     df_comp_main <- df_comp %>%
#       dplyr::mutate(
#         AlgalGroup = dplyr::case_when(per < 5 ~ 'Other',
#                                       TRUE ~ AlgalGroup)
#       ) %>%
#       dplyr::group_by(!!!group_var) %>%
#       dplyr::summarise(per = sum(per),
#                        Units_per_mL = sum(Units_per_mL)) %>%
#       dplyr::distinct()
#     
#     df_return <- df_comp_main
#     
#   } else if (type == 'other'){
#     few_taxa <- df_comp$AlgalGroup[df_comp$per < 5]
#     
#     df_comp_sub <- df %>%
#       dplyr::filter(AlgalGroup %in% few_taxa) %>%
#       dplyr::group_by(!!!group_var) %>%
#       dplyr::summarise(tot = nrow(.),
#                        count = dplyr::n(),
#                        per_other = 100*(dplyr::n() / nrow(.)),
#                        Units_per_mL = sum(Units_per_mL)) %>%
#       dplyr::distinct() %>%
#       dplyr::left_join(., df_comp, by = c('AlgalGroup','count'))
#     
#     df_return <- df_comp_sub
#   }
#   
#   return(df_return)
# }
```

```{r}
# cur version?

# alg_dfs <- function(df, type, region){
#   if (region != 'none'){
#     df <- df %>%
#       dplyr::filter(Region == region) %>%
#       dplyr::mutate(Month = factor(months(SampleDate), levels = month.name, labels = month.abb))
#     
#     group_var <- dplyr::quos(AlgalGroup, Region)
#   } else {
#     group_var <- dplyr::quos(AlgalGroup)
#   }
#   
#   df_defineother <- df %>%
#     dplyr::mutate(AlgalGroup =
#                     dplyr::case_when(grepl('Diatoms', AlgalGroup) ~ 'Diatoms',
#                                      TRUE ~ AlgalGroup)) %>%
#     dplyr::group_by(AlgalGroup) %>%
#     dplyr::summarise(
#       tot = nrow(.),
#       count = dplyr::n(),
#       per = 100 * (dplyr::n() / nrow(.)),
#       Units_per_mL = sum(Units_per_mL),
#     ) %>%
#     dplyr::distinct() %>%
#     dplyr::mutate(OtherAlgalGroup = dplyr::case_when(per < 5 ~ 'Other',
#                                                 TRUE ~ AlgalGroup))
#                   
#   taxa_other <- df_defineother$AlgalGroup[df_defineother$OtherAlgalGroup == 'Other']
#   print(taxa_other)
#   
#   if (region != 'none'){
#         group_var <- dplyr::quos(AlgalGroup, Region, Month)
#   }
#   
#   df_comp <- df %>%
#     dplyr::mutate(
#       AlgalGroup =
#         dplyr::case_when(grepl('Diatoms', AlgalGroup) ~ 'Diatoms',
#                          TRUE ~ AlgalGroup)
#     ) %>%
#     dplyr::group_by(!!!group_var) %>%
#     dplyr::summarise(tot = nrow(.),
#                      count = dplyr::n(),
#                      per = 100*(dplyr::n() / nrow(.)),
#                      Units_per_mL = sum(Units_per_mL)) %>%
#     dplyr::distinct()
#   
#   if(type == 'raw'){
#     df_return <- df_comp
#     
#   } else if (type == 'main'){
#     df_comp_main <- df_comp %>%
#       dplyr::mutate(
#         AlgalGroup = dplyr::case_when(AlgalGroup %in% taxa_other ~ 'Other',
#                                       TRUE ~ AlgalGroup)
#       ) %>%
#       dplyr::group_by(!!!group_var) %>%
#       dplyr::summarise(per = sum(per),
#                        Units_per_mL = sum(Units_per_mL)) %>%
#       dplyr::distinct()
#     
#     df_return <- df_comp_main
#     
#   } else if (type == 'other'){
#     few_taxa <- df_comp$AlgalGroup[df_comp$per < 5]
#     
#     df_comp_sub <- df %>%
#       dplyr::filter(AlgalGroup %in% few_taxa) %>%
#       dplyr::group_by(!!!group_var) %>%
#       dplyr::summarise(tot = nrow(.),
#                        count = dplyr::n(),
#                        per_other = 100*(dplyr::n() / nrow(.)),
#                        Units_per_mL = sum(Units_per_mL)) %>%
#       dplyr::distinct() %>%
#       dplyr::left_join(., df_comp, by = c('AlgalGroup','count'))
#     
#     df_return <- df_comp_sub
#   }
#   
#   return(df_return)
# }
```

