# Data Links {#data-links}

## Complete Datasets {.unlisted .unnumbered}
[**Continuous Water Quality**](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.1177.2)

Contact: Michelle Nelson (michelle.nelson@water.ca.gov)

[**Discrete Water Quality**](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=458&revision=7)

Contact: Morgan Battey (morgan.battey@water.ca.gov)

[**Benthic Invertebrates**](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.1036.2)

Contact: Betsy Wells (elizabeth.wells@water.ca.gov)

[**Phytoplankton**](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.1320.3)

Contact: Tiffany Brown (tiffany.brown@water.ca.gov)

[**Zooplankton**](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=522&revision=11)

Contact: Arthur Barros (arthur.barros@wildlife.ca.gov)

## Individual Stations (Continuous Water Quality) {.unlisted .unnumbered}
:::: {style="display: flex;"}

::: {}
[**San Joaquin River near Vernalis @ SJR Club**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=SJR)  

[**Sacramento River below Rio Vista Bridge**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=RVB)

[**Suisun Bay – Martinez**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=MRZ)

[**Suisun Bay – Cutoff Near Ryer**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=RYC)

[**Sacramento River @ Mallard Island**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=MAL)

[**San Joaquin River @ Antioch**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=ANH)

[**Franks Tract – Mid Tract**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=FRK)

[**SJR – Prisoner-Rough & Ready**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=RRI) 
:::

::: {}
&emsp;&nbsp;[**Sacramento River @ Hood**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=SRH)

&emsp;&nbsp;[**San Joaquin River @ Mossdale Bridge**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=MSD)

&emsp;&nbsp;[**Grizzly Bay**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=GZL)

&emsp;&nbsp;[**Honker Bay**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=HON)

&emsp;&nbsp;[**Sacramento River near Sherman Island**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=SSI)

&emsp;&nbsp;[**San Joaquin River @ Twitchell Island**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=TWI)

&emsp;&nbsp;[**SJR – Prisoner's Point**](https://cdec.water.ca.gov/dynamicapp/QueryF?s=PPT)
:::

::::
<br>
Contact: Andrew Tran (andrew.tran@water.ca.gov)

## Related Datasets {.unlisted .unnumbered}
[**Integrated San Francisco Estuary Discrete Water Quality**](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=731)

Contact: Sam Bashevkin (sam.bashevkin@waterboards.ca.gov)
