---
title: ""
output: 
  html_document:
    includes:
       in_header: admin/analytics.html
---

## Metadata

### Period of Record {.unlisted .unnumbered}
Benthic monitoring began in 1975. From 1975 through 1979 the program collected samples biannually from 18 to 35 stations, for a total of 48 stations over the period. In reviewing data collected between 1975 and 1979, it became evident that semi annual monitoring was insufficient to reveal long term ecological changes as mandated by Water Right Decision 1485. In 1980, DWR revised the benthic monitoring program and began monthly sampling at nine stations. In 1995, major program revisions were implemented to the program. A review of the data collected from 1980 to 1990 recommended that across-channel sampling be reduced to a single station per location in the Delta so that the geographic coverage could be widened. These revisions included increasing the number of sites sampled each month from nine to ten and increasing the number of grab sample replicates from three to four. Detailed information about location, number and characteristics of the historical sites can be found in IEP Technical Report 12 (Markmann, 1986) and IEP Technical Report 38 (Hymanson, et al., 1994). 
A programmatic review of the EMP in 2001-2002 found that the benthos monitoring element was particularly in need of fundamental and comprehensive consideration through intense special studies and study design examination. Reviewers recommended a temporary reduction in sampling frequency to free up EMP resources to conduct the more spatially intense sampling without requiring additional resources. October 2003 was the last of the monthly sampling events and sampling continued quarterly (in October, January, April, July) at the stations sampled through October 2005 when monthly sampling resumed. 

### Sampling Frequency {.unlisted .unnumbered}
Biannual sampling was conducted in late spring and fall, from 1975 to 1979. Monthly sampling started in June 1980 and ended in October 2003. Samples were collected quarterly from October 2003 through October 2005. Currently samples are collected monthly. 

### Sample Sites {.unlisted .unnumbered}
A list of the stations at which benthic invertebrate sampling has occurred is available
```{r echo=FALSE}
xfun::embed_file(path = 'sections/benthic/data/benthic_site_locs.xlsx', name = 'benthic_site_locs.xlsx', text = 'here.')
```
Note: Coordinates are in decimal degrees, and channel position is determined while facing downstream.

### Field Collection Methods {.unlisted .unnumbered}
<b>Benthos</b>

All samples are collected using a hydraulic winch and Ponar dredge. The Ponar dredge samples a bottom area of about 0.052 m2 to a depth that varies with the type of sediment and the ability of the dredge to penetrate it. Under the current program four replicate sample grabs are collected at each sampling site. The contents of the dredge are brought to the surface and placed in a large plastic bucket. Water is then added to the sample to create slurry. The contents of each grab sample bucket are washed over Standard No. 30 stainless steel mesh screen (0.595 mm openings). Each sample is carefully washed with a fine spray to remove as much of the substrate as possible. All material remaining on the screen after washing is preserved in a solution of approximately 20% buffered formaldehyde containing Rose Bengal dye for laboratory analysis. The benthic macroinvertebrate sampling methodology used in this program is described in Standard Methods for the Examination of Water and Wastewater, 20th ed. 1998 American Public Health Association, Washington D.C. (See pages 10-60 through 10-74.) 

<b>Sediment</b>

Sediment samples are also collected as part of the benthic monitoring program. Samples are collected using the same hydraulic winch and Ponar dredge as the infaunal sampling. A single sediment grab is taken at each sampling site. The contents of the Ponar dredge are emptied into a plastic tub and a random subsample is placed into a 1-liter plastic jar for storage and transport to the DWR Soils Laboratory for analysis. 

### Lab Processing Methods {.unlisted .unnumbered}
<b>Benthos</b>

At the laboratory, the volume of settleable substrate in each sample jar is estimated and recorded. The formalin fixative is poured off and the sample is thoroughly washed on a 30-mesh (0.6 mm) screen. The composition of the substrate is estimated and recorded noting the relative percentages of peat, sand, mica, organic detritus, and other materials. The substrate is hand picked for organisms under a three diopter illuminated magnifier. Organisms are placed in 70% ethyl alcohol for subsequent identification. A stereoscopic dissecting microscope (70-120x) is used to identify most organisms. When taxonomic features are too small for identification under the dissecting scope, the organism is permanently mounted on a slide and examined under a compound microscope. If more than four hours of picking is required, and a sample contains many organisms but few species, a one-fourth subsample is chosen at random. The subsample is picked and the results are multiplied by four to represent the total sample. The remainder of the sample is inspected to make sure no other taxa were overlooked. Laboratory identification and enumeration of macro-benthic organisms in each sample is performed under contract by Hydrozoology Laboratory, P.O. Box 682 Newcastle, CA 95658. Analysis has been done by Hydrozoology for the program's entire period of record.

<b>Sediment</b>

All sediment samples are analyzed by the DWR Soils Laboratory, West Sacramento, CA. Analysis of a sediment sample involves determining the percent size fractions with the use of a mechanical sieve. The sieves sizes are as follow: 75, 37.5, 19, 9.5, 4.75, 2.36, 1.18, 0.6, 0.3, 0.15, 0.075, 0.005, 0.002, 0.001 mm. All particle sizes are found on a regular basis in the samples with the exception of gravel (particles greater than 4.76 mm in diameter). The percent organic content of each sediment sample is also determined from the loss in weight of an oven-dried sample burned at 440 degrees Celsius for 8 hours. All laboratory analysis procedures follow the American Society for Testing Methods, D-2974, "Moisture, Ash, and Organic Matter "and D-422-63, "Particle-Size Analysis of Soil". 

### Works Cited {.unlisted .unnumbered}

Hymanson, Z., D. Mayer and J. Steinbeck. 1994. Long-Term Trends in Benthos Abundance and Persistence in the Upper Sacramento-San Joaquin Estuary, Summary Report: 1980-1990. IEP Technical Report 38. 68 pp.

Markmann, C. 1986. Benthic Monitoring in the Sacramento-San Joaquin Delta. Results from 1975 through 1981. IEP Technical Report 12. 51 pp. 