project:
  type: default
  output-dir: _pdfs
  execute-dir: project

format:
  pdf:
    documentclass: article
    papersize: letter
    geometry:
      - margin=1in
    toc: false
    keep-tex: true
    number-sections: true
    colorlinks: true
    fig-pos: 'H'
    tbl-pos: 'H'
    # include-in-header:
    #   text: |
    #     \usepackage[section]{placeins}
    #     \setlength{\intextsep}{30pt plus 2pt minus 4pt}
    #     \setlength{\textfloatsep}{20pt plus 2pt minus 4pt}
    #     \setlength{\floatsep}{20pt plus 2pt minus 4pt}

execute:
  echo: false
  warning: false
  message: false