project:
  type: default
  output-dir: _pdfs
  execute-dir: project
  pre-render: _copy_pdf_resources.R

format:
  pdf:
    documentclass: article
    papersize: letter
    geometry:
      - margin=1in
    toc: true
    number-sections: true
    colorlinks: true

execute:
  echo: false
  warning: false
  message: false