suppressPackageStartupMessages({
  library(conflicted)
  library(R6)
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(tibble)
  library(cowplot)
  library(xml2)
  library(ggplot2)
  library(readr)
  library(stringr)
  library(forcats)
  library(glue)
  library(lubridate)
  library(rlang)
  library(here)
  library(scales)
  library(colorspace)
  library(RColorBrewer)
  library(patchwork)
  library(ggborderline)
  library(treemapify)
  library(knitr)
  library(kableExtra)
  library(openxlsx)
  library(rvest)
  library(jsonlite)
  library(plotly)
  library(htmltools)
  library(magrittr)
})
  
conflict_prefer('filter', 'dplyr', quiet = TRUE)
conflict_prefer('lag', 'dplyr', quiet = TRUE)
conflict_prefer('intersect', 'dplyr', quiet = TRUE)
conflict_prefer('setdiff', 'dplyr', quiet = TRUE)
conflict_prefer('setequal', 'dplyr', quiet = TRUE)
conflict_prefer('union', 'dplyr', quiet = TRUE)
conflict_prefer('date', 'lubridate', quiet = TRUE)