project:
  type: website
  output-dir: _site
  execute-dir: project
  pre-render: _copy_site_resources.R
  render:
    - "*.qmd"
    - "**/*.qmd"
  resources:
    - assets/**
    - admin/figures-tables/**

execute:
  freeze: auto

website:
  page-navigation: false
  title: 'Environmental Monitoring Program'
  favicon: assets/sentinel.ico

  page-footer:
    background: '#e8f1f5'
    center: |
      ![](/assets/EMP_footer.png){fig-alt="DWR, CDFW, and USBR logos" height=50px}

  navbar:
    background: '#e8f1f5'
    foreground: '#006699'
    logo: assets/EMP_logo.png
    logo-alt: 'EMP logo'
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd

      - text: "Data Links"
        href: general/data-links.qmd

      - text: "Annual Reports"
        menu:
          - text: "Continuous Water Quality"
            href: cwq/cwq-report.qmd
          - text: "Discrete Water Quality"
            href: dwq/dwq-report.qmd
          - text: "Benthic Invertebrates"
            href: benthic/benthic-report.qmd
          - text: "Phytoplankton"
            href: phyto/phyto-report.qmd
          - text: "Zooplankton"
            href: zoop/zoop-report.qmd

      - text: "Special Studies"
        menu:
          - text: "Veliger Monitoring Program"
            href: special-studies/veliger-info.qmd
          - text: "Golden Mussel Sightings"
            href: special-studies/golden-mussels.qmd

      - text: "Contact Us"
        href: "mailto:ted.flynn@water.ca.gov"

format:
  html:
    theme: cosmo
    css:
      - assets/styles.css
    include-in-header:
      - assets/includes/analytics.html
    toc: true
    toc-title: Contents
    page-layout: full