```{r Info}
# Benthic IEP Template
# Purpose: create graphs/compute summary statistics for benthic data
# Author: Sarah Perry
# Contact: sarah.perry@water.ca.gov
```

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_knit$set(root.dir = './02_Benthic/annual-report/')
```

```{r Variables to Edit}
# workbook
wkbk_raw <- 'Data/2021 benthic annual report data.csv'
```

-- CODE STARTS HERE --

```{r Load Packages warning=FALSE, message=FALSE}
# import packages
library(RColorBrewer)
library(tidyverse)
library(lubridate)
library(openxlsx)
library(ggplot2)
library(zoo)
```

```{r Define Functions}
# add sheet to workbook
add_sheet <- function(wb, df, sheet_name) {
  openxlsx::addWorksheet(wb, sheet_name)
  openxlsx::writeData(wb, sheet_name, df, startRow = 1, startCol = 1)
}

# blank theme for plots
blank_theme <- function(){
  theme_bw() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text = element_text(color = 'black', size = 8, family = 'sans'),
      axis.text.x = element_text(angle = 45, vjust=0.5, margin = margin(t = 1)),
      strip.text.x = element_text(size = 8),
      axis.title = element_text(size = 9.5, face = 'bold'),
      plot.title = element_blank(),
      legend.position = 'right',
      legend.box = 'vertical',
      legend.title = element_blank(),
      legend.title.align = 0,
      legend.box.margin = margin(-5,0,0,0),
      legend.spacing.y = unit(-0.2, 'cm'),
      legend.text = element_text(size = 8)
    )
}
```

```{r Import and Clean Data}
# read in data
df_benthic <- read_csv(wkbk_raw)

# create workbook for new data
wkbk_export <- createWorkbook()

# append raw data to new xlsx
add_sheet(wkbk_export, df_benthic, 'Raw Data')

# add date col
# df_benthic$Date <- as.yearmon(paste(df_benthic$Month, df_benthic$Year))
df_benthic <- df_benthic %>% rename(Date = SampleDate)
df_benthic$Date <- as.Date(df_benthic$Date, format = '%m/%d/%Y')

# remove dashes in station names
df_benthic$StationCode <- unlist(lapply(df_benthic$StationCode, function(x) str_split(x, '-')[[1]][1]))

# factor stations by figure order
station_factor <- c('D24','D16','D28A','P8','C9','D4','D6','D7','D41','D41A')
df_benthic$StationCode <- factor(df_benthic$StationCode, levels = station_factor)

# list of classification col names
classif <- c('Phylum','Class','Order','Family','Genus','Species')

# grab report year (for saving purposes)
report_year <- as.integer(format(Sys.Date(), '%Y'))-1

# create a plots dir (for saving purposes)
years_ts_dir <- paste0(report_year,' Plots/years_timeseries')
ry_ts_dir <- paste0(report_year,' Plots/',report_year,'_timeseries')
ry_bar_dir <- paste0(report_year,' Plots/',report_year,'_bargraphs')

dir_list <- c(years_ts_dir, ry_ts_dir, ry_bar_dir)

for (dir in dir_list){
  dir.create(file.path(dir), recursive = TRUE)
}
# TODO: check if directory exists
```

```{r All Years & All Stations Timeseries}
# ---  Calculate Monthly/Yearly Totals ---
# create df of totals by month per station
df_month_stat <- df_benthic %>%
  group_by(Month, Year, StationCode) %>%
  mutate(GrabCount_MonthStat = length(unique(Grab))) %>%
  ungroup() %>%
  group_by(.dots = c(classif, 'Month', 'Year', 'StationCode', 'GrabCount_MonthStat')) %>%
  summarize(OrgsTotal_MonthStat = sum(Count, na.rm = TRUE), .groups = 'drop') %>%
  mutate(Date = paste(Month, Year)) # TODO: explore adding in day as well

# get grab variable per station per year
df_grabvari_month <- df_month_stat %>%
  distinct(Date, Month, Year, StationCode, GrabCount_MonthStat) %>%
  group_by(Year, Month, StationCode) %>%
  summarize(GrabCount_MonthStat = sum(GrabCount_MonthStat), .groups = 'drop') %>%
  group_by(Month, Year) %>%
  mutate(GrabCount_Month = sum(GrabCount_MonthStat)) %>%
  ungroup() %>%
  group_by(Year, StationCode) %>%
  mutate(GrabCount_YearStat = sum(GrabCount_MonthStat))

df_grabvari_year <- df_month_stat %>%
  distinct(Date, Year, StationCode, GrabCount_MonthStat) %>%
  group_by(Year, StationCode) %>%
  summarize(GrabCount_YearStat = sum(GrabCount_MonthStat), .groups = 'drop') %>%
  group_by(Year) %>%
  mutate(GrabCount_Year = sum(GrabCount_YearStat)) %>%
  ungroup()

# create df of totals by year per station
df_year_stat <- df_month_stat %>%
  group_by(.dots = c(classif, 'Year','StationCode')) %>%
  summarize(OrgsTotal_YearStat = sum(OrgsTotal_MonthStat, na.rm = TRUE), .groups = 'drop')

df_year_stat <-  merge(df_year_stat, df_grabvari_year, by = c('Year','StationCode'), all.x=FALSE, all.y=FALSE)

df_month_stat <- df_month_stat %>% select(-c('GrabCount_MonthStat'))

df_month_stat <- merge(df_month_stat, df_grabvari_month, by = c('Year','Month','StationCode'), all.x=FALSE, all.y=FALSE)

# calc CPUE
df_month_stat <- df_month_stat %>%
  group_by(.dots = c(classif, 'Month', 'Year', 'StationCode')) %>% # TODO: redundant, check after confirming right
  mutate(CPUETotal_MonthStat = OrgsTotal_MonthStat/GrabCount_MonthStat/0.052,
         CPUETotal_Month = OrgsTotal_MonthStat/GrabCount_Month/0.052) %>%
  ungroup()

df_year_stat <- df_year_stat %>%
  group_by(.dots = c(classif, 'Year', 'StationCode')) %>%
  mutate(CPUETotal_YearStat = OrgsTotal_YearStat/GrabCount_YearStat/0.052,
         CPUETotal_Year = OrgsTotal_YearStat/GrabCount_Year/0.052) %>%
  ungroup()

df_year_stat <- df_year_stat[!df_year_stat$Phylum == 'n/a',] # TODO: need to fix in future versions of csv
df_month_stat <- df_month_stat[!df_month_stat$Phylum == 'n/a',]

df_month <- df_month_stat %>%
  group_by(.dots = c(classif, 'Month', 'Year')) %>%
  summarize(CPUETotal_Month = sum(CPUETotal_Month, na.rm = TRUE),
            OrgsTotal_Month = sum(OrgsTotal_MonthStat, na.rm = TRUE),
            .groups = 'drop')

df_year <- df_year_stat %>%
  group_by(.dots = c(classif, 'Year')) %>%
  summarize(CPUETotal_Year = sum(CPUETotal_Year, na.rm = TRUE),
         OrgsTotal_Year = sum(OrgsTotal_YearStat, na.rm = TRUE),
         .groups = 'drop')

# append to workbook
add_sheet(wkbk_export, df_year, 'Yearly Totals (All)')
add_sheet(wkbk_export, df_month, 'Monthly Totals (All)')

# --- Create Timeseries ---
# add a name col to year
df_year$Name <- with(df_year, paste(Phylum, Genus, Species))

df_year_top <- df_year %>%
  subset(Year >= report_year - 10) %>%
  group_by(Name) %>%
  mutate(TotalSum = sum(CPUETotal_Year)) %>%
  arrange(desc(TotalSum)) %>%
  ungroup()

df_year_top <- df_year_top[df_year_top$TotalSum %in% unique(df_year_top$TotalSum)[1:15],]

# complete cases
suppressWarnings(df_year_top <- df_year_top %>% complete(Year, nesting(Name, TotalSum)))
df_year_top$CPUETotal_Year[is.na(df_year_top$CPUETotal_Year)] = 0
df_year_top$TotalSum[is.na(df_year_top$TotalSum)] = 0

# re-order
df_year_top$Name <- with(df_year_top, reorder(Name, TotalSum))

# plot
colorCount = length(unique(df_year_top$Name))
getPalette = colorRampPalette(brewer.pal(8, 'Set2'))

plt <- ggplot(df_year_top, aes(Year, CPUETotal_Year, group = Name)) +
  geom_line(aes(color = Name), size = 1) +
  geom_point(aes(color = Name), size = 1.7) +
  scale_color_manual(values = getPalette(colorCount)) +
  ylab(expression('Individuals/m'^2)) +
  guides(color = guide_legend(reverse = TRUE)) +
  blank_theme() 

ggsave(paste0(years_ts_dir,'/CPUE_all.png'), plot = plt, width = 8, height = 4)

rm(df_year_top, plt)
```

```{r Specific Stations Timeseries}
# --- Create All Years Timeseries ---
# subset top 10 species by average CPUE over all years
df_year_stat$Name <- with(df_year_stat, paste(Phylum, Genus, Species))

df_year_stat_top <- df_year_stat %>%
  group_by(Name, StationCode) %>%
  mutate(TotalSum = sum(CPUETotal_Year, na.rm = TRUE)) %>%
  arrange(Year, StationCode, desc(TotalSum)) %>%
  ungroup() %>%
  select(-c(CPUETotal_Year, GrabCount_Year))

# append to workbook
add_sheet(wkbk_export, subset(df_year_stat_top, select = -c(Name, TotalSum)), 'Yearly Totals (Stations)')

for (station in unique(df_year_stat_top$StationCode)){
  # filter by station
  df_filt <- df_year_stat_top %>%
    filter(StationCode == station) %>%
    mutate(CPUESum_Year = sum(CPUETotal_YearStat)) %>%
    group_by(Name) %>%
    mutate(Percentage = round(sum(CPUETotal_YearStat)/CPUESum_Year*100,2)) %>%
    ungroup()

  # subset species that are top 10 (average CPUE over all years)
  df_filt <- df_filt[df_filt$Percentage %in% unique(df_filt$Percentage)[1:10],]
  
  # complete missing cases
  df_filt <- df_filt %>% complete(Year, nesting(Name, StationCode, Percentage))
  
  df_filt$CPUETotal_YearStat[is.na(df_filt$CPUETotal_YearStat)] = 0
  df_filt$Percentage[is.na(df_filt$Percentage)] = 0

    # re-order
  df_filt$Name  <- with(df_filt, reorder(Name, Percentage))
  
  # set color palette
  colorCount = length(unique(df_filt$Name))
  getPalette = colorRampPalette(brewer.pal(8, 'Set2'))

  # plot
  plt <- ggplot(df_filt, aes(Year, CPUETotal_YearStat, group = Name)) +
    geom_line(aes(color = Name), size = 1) +
    geom_point(aes(color = Name), size = 1.7) +
    scale_color_manual(values = getPalette(colorCount)) +
    ylab(expression(bold('Individuals/m'^2))) +
    guides(color = guide_legend(reverse = TRUE)) +
    blank_theme() 

  ggsave(paste0(years_ts_dir,'/CPUE_',station,'.png'), plot = plt, width = 8, height = 4)
}


# --- Create Report Year Timeseries ---
# add a name col to year
df_month_stat$Name <- with(df_month_stat, paste(Phylum, Genus, Species))

# subset top 10 species by average CPUE over all months in a given year
df_month_stat_top <- df_month_stat %>%
  group_by(Name, StationCode, Year) %>%
  mutate(TotalSum = sum(CPUETotal_MonthStat, na.rm = TRUE)) %>%
  arrange(Year, StationCode, desc(TotalSum)) %>%
  ungroup()

# factor month col
df_month_stat_top$Month = factor(df_month_stat_top$Month, levels = month.name)

# arrange df
df_month_stat_top <- df_month_stat_top %>%
  arrange(Year, Month, StationCode, desc(TotalSum)) %>%
  select(-c(CPUETotal_Month, GrabCount_Month, GrabCount_YearStat))

# append to workbook 
add_sheet(wkbk_export, subset(df_month_stat_top, select = -c(Name, TotalSum)), 'Monthly Totals (Stations)')

# create timeseries only for report year
for (station in unique(df_month_stat_top$StationCode)){
  # filter df by report year and station
  df_filt <- df_month_stat_top %>%
    filter(StationCode == station,
           Year == report_year) %>%
    group_by(StationCode) %>%
    mutate(CPUESum_Month = sum(CPUETotal_MonthStat)) %>%
    ungroup %>%
    group_by(Name) %>%
    mutate(Percentage = round(sum(CPUETotal_MonthStat)/CPUESum_Month*100,2)) %>%
    ungroup %>%
    arrange(desc(Percentage))

  # filter out top ten species
  df_filt <- df_filt[df_filt$Percentage %in% unique(df_filt$Percentage)[1:10],]
  df_filt <- df_filt[df_filt$Percentage >= 1,]
  
  # complete missing cases
  df_filt <- df_filt %>% complete(Year, nesting(Name, StationCode, Percentage))
  
  df_filt$CPUETotal_MonthStat[is.na(df_filt$CPUETotal_MonthStat)] = 0
  df_filt$Percentage[is.na(df_filt$Percentage)] = 0

  # re-order
  df_filt$Name  <- with(df_filt, reorder(Name, TotalSum))

  # define color scheme
  colorCount = length(unique(df_filt$Name))
  getPalette = colorRampPalette(brewer.pal(8, 'Set2'))
  
  # plot timeseries
  ts <- ggplot(df_filt, aes(Month, CPUETotal_MonthStat, group = Name)) +
    geom_line(aes(color = Name), size = 1) +
    geom_point(aes(color = Name), size = 1.7) +
    scale_color_manual(values = getPalette(colorCount)) +
    ylab(expression(bold('Individuals/m'^2))) +
    guides(color = guide_legend(reverse = TRUE)) +
    blank_theme() 

  ggsave(paste0(ry_ts_dir,'/CPUE_',station,'.png'), plot = ts, width = 8, height = 4)
}

rm(df_month_stat_top, df_year_stat_top)
```

```{r Top Species for RY Tabs}
# filter by year
df_report_year <- df_year %>%
  filter(Year == report_year) %>%
  mutate(CPUESum_Year = sum(CPUETotal_Year)) %>%
  group_by(Genus, Species) %>%
  mutate(Percentage = round(CPUETotal_Year/CPUESum_Year*100, 2)) %>%
  arrange(desc(OrgsTotal_Year))

df_report_year_stat <- df_year_stat %>%
  filter(Year == report_year) %>%
  group_by(StationCode) %>%
  mutate(CPUESum_YearStat = sum(CPUETotal_YearStat)) %>%
  ungroup() %>%
  group_by(Genus, Species, StationCode) %>%
  mutate(Percentage = round(CPUETotal_YearStat/CPUESum_YearStat*100, 2)) %>%
  arrange(StationCode, desc(OrgsTotal_YearStat))

df_report_month <- df_month %>%
  filter(Year == report_year) %>%
  group_by(Month) %>%
  mutate(CPUESum_Month = sum(CPUETotal_Month)) %>%
  ungroup() %>%
  group_by(Genus, Species, Month) %>%
  mutate(Percentage = round(CPUETotal_Month/CPUESum_Month*100, 2))

df_report_month$Month = factor(df_report_month$Month, levels = month.name)

df_report_month <- df_report_month %>%
  arrange(Month, desc(OrgsTotal_Month))

df_report_month_stat <- df_month_stat %>%
  filter(Year == report_year) %>%
  group_by(Month, StationCode) %>%
  mutate(CPUESum_Month = sum(CPUETotal_Month)) %>%
  ungroup() %>%
  group_by(Genus, Species, Month, StationCode) %>%
  mutate(Percentage = round(CPUETotal_Month/CPUESum_Month*100, 2)) %>%
  arrange(StationCode, desc(OrgsTotal_MonthStat))

df_report_month_stat$Month = factor(df_report_month_stat$Month, levels = month.name)

df_report_month_stat <- df_report_month_stat %>%
  arrange(StationCode, Month, desc(OrgsTotal_MonthStat))

# subset out year cols
df_report_year <- subset(df_report_year, select = -c(Name, Year, CPUESum_Year))

df_report_year_stat <- subset(df_report_year_stat, select = -c(Name, Year, CPUESum_YearStat, CPUETotal_Year))

df_report_month <- subset(df_report_month, select = -c(Year, CPUESum_Month))

df_report_month_stat <- subset(df_report_month_stat, select = -c(Name, Year, CPUESum_Month, CPUETotal_Month))

# add to workbook
add_sheet(wkbk_export, df_report_year, paste(report_year,'Species (Year) (All)'))

add_sheet(wkbk_export, df_report_month, paste(report_year,'Species (Month) (All)'))

add_sheet(wkbk_export, df_report_year_stat, paste(report_year,'Species (Year) (Stations)'))

add_sheet(wkbk_export, df_report_month_stat, paste(report_year,'Species (Month) (Stations)'))

# remove extra stuff
rm(df_year, df_month, df_month_stat, df_year_stat)

df_report_month <- subset(df_report_month, select = -c(Percentage))

df_report_month_stat <- subset(df_report_month_stat, select = -c(Percentage))

```

```{r Create RY Bargraphs  and Calc Phylums}
# --- Calc Phylums by Month ---
# condense by phylum (all months)
df_ry_phy <- df_report_month %>%
  group_by(Phylum, Month) %>%
  summarize(OrgsTotal_Month = sum(OrgsTotal_Month), CPUETotal_Month = sum(CPUETotal_Month)) %>%
  ungroup() %>%
  group_by(Month) %>%
  mutate(SumTotal_Month = sum(OrgsTotal_Month)) %>%
  ungroup() %>%
  group_by(Phylum, Month) %>%
  mutate(Percentage = round(OrgsTotal_Month/SumTotal_Month*100,2)) %>%
  ungroup()

# remove extra col
df_ry_phy <- subset(df_ry_phy, select = -c(SumTotal_Month))

# factor month col
df_ry_phy$Month = factor(df_ry_phy$Month, levels = month.name)

# arrange df
df_ry_phy <- df_ry_phy %>%
  arrange(Month, desc(Percentage))

# condense by phylum per station (all months)
df_ry_stat_phy <- df_report_month_stat %>%
  group_by(Phylum, StationCode, Month) %>%
  summarize(OrgsTotal_MonthStat = sum(OrgsTotal_MonthStat), CPUETotal_MonthStat = sum(CPUETotal_MonthStat)) %>%
  ungroup() %>%
  group_by(StationCode, Month) %>%
  mutate(SumTotal_MonthStat = sum(OrgsTotal_MonthStat)) %>%
  ungroup() %>%
  group_by(Phylum, StationCode, Month) %>%
  mutate(Percentage = round(OrgsTotal_MonthStat/SumTotal_MonthStat*100,2)) %>%
  ungroup()

# remove extra col
df_ry_stat_phy <- subset(df_ry_stat_phy, select = -c(SumTotal_MonthStat))

# factor month col
df_ry_stat_phy$Month = factor(df_ry_stat_phy$Month, levels = month.name)

# add color col
df_ry_stat_phy <- df_ry_stat_phy %>%
  mutate(
    Color =
      case_when(
        Phylum == 'Mollusca' ~ '#8da0cb',
        Phylum == 'Arthropoda' ~ '#fc8d62',
        Phylum == 'Annelida' ~ '#66c2a5',
        Phylum == 'Nematoda' ~ '#e78ac3',
        Phylum == 'Phoronida' ~ '#a6d854',
        Phylum == 'Cnidaria' ~ '#ffd92f',
        Phylum == 'Chordata' ~ '#fb9a99',
        Phylum == 'Nemertea' ~ '#d9d9d9',
        Phylum == 'Platyhelminthes' ~ '#d9d9d9',
        Phylum == 'Echinodermata' ~ '#bc80bd',
        Phylum == 'Nematomorpha' ~ '#8dd3c7'
      )
  )

# df_ry_stat_phy$Color <- as.factor(df_ry_stat_phy$Color)
df_ry_stat_phy$Phylum <- as.factor(df_ry_stat_phy$Phylum)

# arrange df
df_ry_stat_phy <- df_ry_stat_phy %>%
  arrange(StationCode, Month, desc(Percentage))

# create graphs
i <- 2

for (station in unique(df_ry_stat_phy$StationCode)){

  df_filt <- df_ry_stat_phy %>%
    filter(StationCode == station)
  
  # check phyla less than 1% of total year
  df_check <- df_filt %>%
    mutate(Total_Check = sum(OrgsTotal_MonthStat)) %>%
    group_by(Phylum) %>%
    mutate(Percent_Check = round(sum(OrgsTotal_MonthStat)/Total_Check*100,2)) %>%
    ungroup()
  
  rare_phyla <- unique(df_check$Phylum[df_check$Percent_Check <= 1])
  
  df_filt <- df_filt[!df_filt$Phylum %in% rare_phyla,]
  
  df_filt$Phylum <- with(df_filt, reorder(Phylum, CPUETotal_MonthStat))
  
  # arrange df
  df_filt <- df_filt %>%
    group_by(StationCode, Phylum) %>%
    mutate(Order = sum(Percentage)) %>%
    arrange(StationCode, Month, Order) %>%
    ungroup()
  
  # graph
  bar <- ggplot(df_filt, aes(Month, CPUETotal_MonthStat, fill = factor(Color, levels = unique(df_filt$Color)))) +
    geom_col(color = 'black') +
    scale_fill_identity(guide = 'legend', labels = rev(df_filt$Phylum), breaks = rev(df_filt$Color)) +
    ylab(expression(bold('Individuals/m'^2))) +
    blank_theme() 
  
  ggsave(paste0(ry_bar_dir,'/Fig',i,'_',station,'.png'), plot = bar, width = 6, height = 3.5)
  
  i <- i + 1
}

# --- Calc Phylums by Year ---
# subset df
df_phy_percs <- df_report_year %>%
  group_by(Phylum) %>%
  summarize(OrgsTotal_Year = sum(OrgsTotal_Year), CPUETotal_Year = sum(CPUETotal_Year)) %>%
  ungroup() %>%
  mutate(SumTotal_Year = sum(OrgsTotal_Year)) %>%
  group_by(Phylum) %>%
  mutate(Percentage = round(OrgsTotal_Year/SumTotal_Year*100,2)) %>%
  ungroup()

df_phy_stat_percs <- df_report_year_stat %>%
  group_by(Phylum, StationCode) %>%
  summarize(OrgsTotal_YearStat = sum(OrgsTotal_YearStat), CPUETotal_YearStat = sum(CPUETotal_YearStat)) %>%
  ungroup() %>%
  group_by(StationCode) %>%
  mutate(Percentage = round(OrgsTotal_YearStat/sum(OrgsTotal_YearStat)*100,2)) %>%
  arrange(StationCode, desc(Percentage))

df_ry_stat_phy <- subset(df_ry_stat_phy, select = -c(Color))

# add sheets
add_sheet(wkbk_export, df_phy_percs, paste(report_year, 'Phylums (Year) (All)'))
add_sheet(wkbk_export, df_ry_phy, paste(report_year,'Phylums (Month) (All)'))
add_sheet(wkbk_export, df_phy_stat_percs, paste(report_year, 'Phylum (Year) (Stations)'))
add_sheet(wkbk_export, df_ry_stat_phy, paste(report_year,'Phylums (Month) (Stations)'))
```

```{r Save Workbook}
# save workbook
saveWorkbook(wkbk_export, file = paste(report_year, 'Benthic IEP Data.xlsx'), overwrite = TRUE)
```

